#!/bin/bash 

#Scrips to see logins
fcolumn=1
scolumn=1

case $1 in
-f) fcolumn=1
;;
-s) scolumn=3
;;
-u) fcolumn=3
;;
-h) echo "
# -h выводит help
# -f сортирует по имени и выводит имя (первая колонка)
# -s сортирует по имени и выводит имя и UID 
# -u сортирует по UID и выводит имя и UID
" 
exit
;;
*) cat /etc/passwd
exit
;;
esac

sort -t : -nk $fcolumn /etc/passwd | cut -f $fcolumn,$scolumn -d :
