#!/bin/bash -x

#Scrips to see logins
sortf=1
sortc=""

help(){
echo -e " 
-h выводит help\n-f сортирует по первой колонке\n
"
exit 0
}

case $1 in
-h) help
;;
-t) sortf=3
    sortc=-n
;;
*) 
;;
esac
getent passwd | sort -k $sortf -t : $sortc | 
while read LINE
do
    login= echo $LINE | cut -f 1 -d :
    uid= echo $LINE | cut -f 3 -d : 
    gid= echo $LINE | cut -f 4 -d : 
    shell= echo $LINE | cut -f 6 -d : 
    home= echo $LINE | cut -f 7 -d :

    echo -e "${login}\t${uid}\t${gid}\t${home}\t${shell}"

done


